blueprints/qa.py
from flask import Blueprint, render_template, request, g, redirect, url_for, flash
from decorators import login_required
from .form import QuestionForm, AnswerForm
from models import QuestionModel, AnswerModel
from exts import db

bp = Blueprint("qa", __name__, url_prefix="/")

@bp.route("/")
def index():
    questions = QuestionModel.query.order_by(db.text("create_time desc")).all()
    return render_template('index.html', questions=questions)

@bp.route("/question/public", methods = ["GET","POST"])
@login_required
def public_question():
    if request.method == 'GET':
        return render_template("public_question.html")
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect("/")
        else:
            flash("标题和内容错误")
            return redirect(url_for("qa.public_question"))

@bp.route("/question/<int:question_id>")
def question_detail(question_id):
    question = QuestionModel.query.get(question_id)
    return render_template("detail.html", question=question)

@bp.route("/answer/<int:question_id>",methods=['POST'])
@login_required
def answer(question_id):
    form = AnswerForm(request.form)
    if form.validate():
        content = form.content.data
        answer_model = AnswerModel(content=content, author=g.user, question_id=question_id)
        db.session.add(answer_model)
        db.session.commit()
        print("123")
        return redirect(url_for("qa.question_detail",question_id=question_id))
    else:
        flash("表单验证失败")
        print("345")
        return redirect(url_for("qa.question_detail", question_id=question_id))

blueprints/user.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify, session, g
from exts import mail, db
from flask_mail import Message
from models import EmailCaptchaModel, UserModel
from datetime import datetime
from .form import RegisterForm, LoginForm
from werkzeug.security import generate_password_hash, check_password_hash
import string
import random


bp = Blueprint("user", __name__, url_prefix="/user")


@bp.route("/login", methods = ['GET', 'POST'])
def login():
    if request.method == "GET":
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        print(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password, password):
                session['user_id'] = user.id
                return redirect("/")
            else:
                flash("邮箱和密码不匹配！")
                return redirect(url_for("user.login"))
        else:
            flash("邮箱和密码格式错误！")
            return redirect(url_for("user.login"))

@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("user.login"))

@bp.route("/register", methods = ['GET', 'POST'])
def register():
    if request.method == "GET":
        print("2")
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        print(request.form)
        if form.validate():
            email = form.email.data
            password = generate_password_hash(form.password.data)
            user_name = form.user_name.data
            user = UserModel(email=email, user_name=user_name, password=password)
            db.session.add(user)
            db.session.commit()

            return redirect(url_for("user.login"))
        else:
            flash(form.errors)
            print(form.password.data)
            print(form.password_confirm.data)
            return render_template("register.html")


@bp.route("/captcha", methods=["POST"])
def get_captcha():
    # GET,POST
    email = request.form.get("email")
    letters = string.ascii_letters + string.digits
    captcha = "".join(random.sample(letters,4))
    print(captcha)
    if email:
        message = Message(
            subject="user_test",
            recipients=[email],
            body=f"【知了问答】您的注册验证码是：{captcha}",
        )
        mail.send(message)
        captcha_model = EmailCaptchaModel.query.filter_by(email = email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.create_time = datetime.now()
            db.session.commit()
        else:
            captcha_model = EmailCaptchaModel(email=email, captcha=captcha)
            db.session.add(captcha_model)
            db.session.commit()
        return jsonify({"code": 200})
    else:
        # code:400
        return jsonify({"code": 400, "message":"请先传递邮箱"})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/bootstrap@4.6.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static',filename='css/init.css') }}">
  {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
      <a class="navbar-brand" href="#">Edward</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('qa.public_question')}}">发布问答</a>
      </li>
        <li class="nav-item ml-2" >
                <form class="form-inline my-2 my-lg-0">
                  <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                </form>
        </li>
    </ul>
      <ul class="navbar-nav">
      {% if user %}
        <li class="nav-item">
          <span class="nav-link">{{ user.user_name }}</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.logout') }}">注销</a>
        </li>
      {%  else  %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.login') }}">登录 </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
        </li>
      {% endif %}
    </ul>
  </div>
  </div>
</nav>
<div class="container">{% block body %}{% endblock %}</div>
</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title %} {{ question.title }} {% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='css/detail.css') }}">
{% endblock %}

{% block body %}
  <div class="row" style="margin-top: 20px">
    <div class="col"></div>
    <div class="col-8" style="background: #fff;padding: 20px;">
      <h3 class="page-title" >{{ question.title }}</h3>
      <p class="question-info">
        <span>作者:{{ question.author.user_name }}</span>
        <span>时间:{{ question.create_time }}</span>
      </p>
      <hr>
      <p class="question-content">{{ question.content }}</p>
      <hr>
      <h4 class="comment-group-title">评论({{ question.answers|length }}):</h4>
      <form action="{{ url_for('qa.answer',question_id=question.id)}}" method="post">
      <input type="hidden" name="quesiton_id" value="{{ question.id }}">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="请填写评论" name="content">
      </div>
        <div class="form-group">
      {%  for message in get_flashed_messages() %}
      <div>
        <div class="text-danger">{{ message }}</div>
      </div>
      {% endfor %}
    </div>
      <div class="form-group" style="text-align: right;">
        <button class="btn btn-primary" >评论</button>
      </div>
    </form>
    <ul class="comment-group">
      {% for answer in question.answers %}
      <li>
        <div class="user-info">
          <img src="{{ url_for('static',filename='images/keai.jpeg')}}" alt="" class="avatar">
          <span class="username">{{answer.author.username}}</span>
          <span class="create-time">{{answer.create_time}}</span>
        </div>
        <p class="comment-content">{{answer.content}}</p>
      </li>
      {% endfor %}

    </ul>
    </div>

    <div class="col"></div>
  </div>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}知了问答-首页{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}

{% block body %}
<div class="row" style="margin-top: 20px;">
<div class="col"></div>
<div class="col-8">
  <ul class="question-ul">
    {% for question in questions %}
    <li>
      <div class="side-question">
        <img class="side-question-avatar" src="{{ url_for('static',filename='images/keai.jpeg')}}" alt="">
      </div>
      <div class="question-main">
        <div class="question-title"><a href="{{ url_for('qa.question_detail',question_id = question.id) }}">{{ question.title }}</a></div>
        <div class="question-content">{{ question.content }}</div>
        <div class="question-detail">
          <span class="question-author">{{ question.author.user_name}}</span>
          <span class="question-time">{{ question.create_time }}</span>
        </div>
      </div>
    </li>
    {%  endfor %}
  </ul>
</div>
<div class="col"></div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}知了问答-登录{% endblock %}

{% block head %}

{% endblock %}

{% block body %}
  <div class="row mt-4">
  <div class="col"></div>
  <div class="col">
    <form method="post" action="{{ url_for('user.login')}}">
    <div class="form-group" >
      <label for="exampleInputEmail1">邮箱</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">密码</label>
      <input type="password" class="form-control" name="password">
    </div>
      <div class="form-group">
      {%  for message in get_flashed_messages() %}
      <div>
        <div class="text-danger">{{ message }}</div>
      </div>
      {% endfor %}
    </div>
    <div class="form-group"><button type="submit" class="btn btn-primary btn-block">立即登录</button></div>
  </form></div>
  <div class="col"></div>
  </div>

{% endblock %}

templates/public_question.html
{% extends "base.html" %}

{% block title %}发布问答{% endblock %}

{% block body %}
  <div class="row" style="margin-top: 20px;">
  <div class="col"></div>
  <div class="col-6">
    <h1 style="text-align: center;">发布问答</h1>
    <form action="{{ url_for('qa.public_question') }}" method="post">
      <div class="form-group">
        <input type="text" class="form-control" name="title" placeholder="请输入标题">
      </div>
      <div class="form-group">
        <textarea class="form-control" name="content" rows="10" placeholder="请输入内容"></textarea>
      </div>
      <div class="form-group">
      {%  for message in get_flashed_messages() %}
      <div>
        <div class="text-danger">{{ message }}</div>
      </div>
      {% endfor %}
    </div>
      <div class="form-group" style="text-align: right;">
      <button class="btn btn-primary">发布</button>
    </div>

    </form>
  </div>

  <div class="col"></div>
  </div>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}知了问答-注册{% endblock %}

{% block head %}
    <script src="{{ url_for('static',filename='jquery/jquery.3.6.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/register.js') }}"></script>

{% endblock %}

{% block body %}
<div class="row mt-4">
  <div class="col"></div>
  <div class="col">
    <form method="post" action="{{ url_for('user.register')}}">
    <div class="form-group">
      <label for="exampleInputEmail1">邮箱</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">验证码</label>
        <div class="input-group">
          <input type="text" class="form-control" name="captcha">
        <div class="input-group-append">
          <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">用户名称</label>
      <input type="text" class="form-control" name="user_name">
   </div>
    <div class="form-group">
      <label for="exampleInputPassword1">密码</label>
      <input type="password" class="form-control" id="exampleInputPassword1" name="password">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">确认密码</label>
      <input type="password" class="form-control" name="password_confirm">
    </div>
    <div class="form-group">
      {%  for message in get_flashed_messages() %}
      <div>
        <div class="text-danger">{{ message }}</div>
      </div>
      {% endfor %}
    </div>
    <div class="form-group"><button type="submit" class="btn btn-primary btn-block">立即注册</button></div>

  </form></div>
  <div class="col"></div>
  </div>
{% endblock %}